[package]
name = "epss-api"
description = "Access the EPSS (Exploit Prediction Scoring System) API."
repository = "https://github.com/alilleybrinker/epss"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
